openapi: 3.0.0
info:
  title: Standort API
  description: Eine API für die Verwaltung von Standorten
  version: 1.0.0
paths:
  /standorte:
    get:
      operationId: getStandorte
      summary: getStandorteBy
      description: gibt eine Liste von Standorten zurück. Es ist auch möglich, nur Standorte eines bestimmten Geschaeftspartners oder eines bestimmten Mitarbeiter zurückzugeben
      parameters:
        - in: query
          name: mitarbeiterId
          schema:
            type: integer
            format: int64
          required: false
          description: Mitarbeiter ID
        - in: query
          name: geschaeftspartnerId
          schema:
            type: integer
            format: int64
          required: false
          description: Geschaeftspartner ID
      responses:
        '200':
          description: ermittelt alle Standorte
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StandortModel'
    post:
      operationId: addStandort
      summary: addStandort
      description: fügt einen neuen Standort hinzu
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StandortModel"
      responses:
        "201":
          description: erfolgreich hinzugefügt
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StandortModel"
  /standorte/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        required: true
        description: Standort ID
    get:
      operationId: getStandortById
      summary: Standort abrufen
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StandortModel"
    put:
      operationId: updateStandort
      description:  Standort aktualisieren
      summary: updateStandort
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StandortModel"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StandortModel"
    delete:
      summary: deleteStandort
      description: Standort löschen
      responses:
        "204":
          description: No Content
          content:
            text/plain:
              schema:
                type: string
  /standorte/{id}/standort-uebernahme:
    put:
      operationId: uebernehmeStandort
      description: uebernehmeStandort
      summary: ermöglicht die Übernahme eines Standortes eines Geschaeftspartners durch einen anderen (6)
      parameters:
        - name: id
          in: path
          description: Id des des zu übernehmenden Standortes
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: geschaeftspartnerId
          schema:
            type: integer
            format: int64
          required: true
          description: ID des übernehmenden Geschaeftspartners
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    StandortModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The unique identifier for the standort.
        geschaeftspartnerId:
          type: integer
          format: int64
          description: ID eines Geschäftspartners.
        name:
          type: string
          minLength: 1
          maxLength: 255
        anschriftModel:
          $ref: './mitarbeiter-api.yaml#/components/schemas/AnschriftModel'
        Mitarbeiter:
          type: array
          items:
            $ref: './mitarbeiter-api.yaml#/components/schemas/MitarbeiterModel'
          description: Liste von Mitarbeitern IDs

